[rank: 0] Global seed set to 0
/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python train.py config_file=conf/ssl4eo_benchmark_oli_sr_cd ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python train.py config_file=conf/ssl4eo_benchmark_oli_sr_cd ...
  rank_zero_warn(
You are using a CUDA device ('NVIDIA A100 80GB PCIe') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Missing logger folder: logs/ssl4eo_benchmark_oli_sr_cdl_unet_resnet18_0.01_ce_0_moco
Traceback (most recent call last):
  File "/home/yichia3/torchgeo/train.py", line 156, in <module>
    main(conf)
  File "/home/yichia3/torchgeo/train.py", line 129, in main
    trainer.fit(model=task, datamodule=datamodule)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 896, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 81, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 162, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/yichia3/torchgeo/torchgeo/datamodules/geo.py", line 404, in setup
    self.train_dataset = self.dataset_class(  # type: ignore[call-arg]
  File "/home/yichia3/torchgeo/torchgeo/datasets/ssl4eo_benchmark.py", line 163, in __init__
    self._verify()
  File "/home/yichia3/torchgeo/torchgeo/datasets/ssl4eo_benchmark.py", line 221, in _verify
    raise RuntimeError(
RuntimeError: Dataset not found in `root=data/ssl4eo_benchmark` and `download=False`, either specify a different `root` directory or use `download=True` to automatically download the dataset.
[rank: 0] Global seed set to 0
/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python train.py config_file=conf/ssl4eo_benchmark_oli_sr_cd ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python train.py config_file=conf/ssl4eo_benchmark_oli_sr_cd ...
  rank_zero_warn(
You are using a CUDA device ('NVIDIA A100 80GB PCIe') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Missing logger folder: logs/ssl4eo_benchmark_oli_sr_cdl_unet_resnet18_0.01_ce_0.1_moco
Traceback (most recent call last):
  File "/home/yichia3/torchgeo/train.py", line 156, in <module>
    main(conf)
  File "/home/yichia3/torchgeo/train.py", line 129, in main
    trainer.fit(model=task, datamodule=datamodule)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 896, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 81, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 162, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/yichia3/torchgeo/torchgeo/datamodules/geo.py", line 404, in setup
    self.train_dataset = self.dataset_class(  # type: ignore[call-arg]
  File "/home/yichia3/torchgeo/torchgeo/datasets/ssl4eo_benchmark.py", line 163, in __init__
    self._verify()
  File "/home/yichia3/torchgeo/torchgeo/datasets/ssl4eo_benchmark.py", line 221, in _verify
    raise RuntimeError(
RuntimeError: Dataset not found in `root=data/ssl4eo_benchmark` and `download=False`, either specify a different `root` directory or use `download=True` to automatically download the dataset.
slurmstepd: error: *** JOB 8969109 ON ccc0284 CANCELLED AT 2023-06-06T17:21:55 ***
